name: build release zip

on:
  release:
    types: [created]

jobs:
  release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1.51
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "go.mod"
          project_path: "./cmd/p4harmonize"
          extra_files: LICENSE.txt README.md
          ldflags:
            '-X "github.com/danbrakeley/p4harmonize/internal/buildvar.Version=${{ github.event.release.tag_name }}"
            -X "github.com/danbrakeley/p4harmonize/internal/buildvar.BuildTime=${{ github.event.release.created_at
            }}" -X "github.com/danbrakeley/p4harmonize/internal/buildvar.ReleaseURL=${{
            github.event.release.html_url }}"'
