name: validate commit
on: [pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2019]
        go-ver: ["1.20"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-ver }}
      - run: go test ./...
      - run: go build ./cmd/p4harmonize
